---
repos:
# Project settings
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.3.0
      hooks:
          - id: check-toml
          - id: check-yaml
    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.1.0
      hooks:
          - id: yamlfmt

# Documentation
    - repo: https://github.com/pre-commit/pygrep-hooks
      rev: v1.7.0
      hooks:
          - id: rst-backticks
          - id: rst-directive-colons
    - repo: https://github.com/asottile/blacken-docs
      rev: v1.8.0
      hooks:
          - id: blacken-docs
    - repo: https://github.com/ldbo/pre-commit-hooks
      rev: master
      hooks:
          - id: lint-markdown

# Python
    - repo: https://github.com/ldbo/pre-commit-hooks
      rev: f263cc5b3dfbab8af3c60f1819b7c2eb066f191d
      hooks:
          - id: mypy
            files: emu/.*\.py
            additional_dependencies: [lxml]
    - repo: https://github.com/PyCQA/isort
      rev: 5.6.4
      hooks:
          - id: isort
            additional_dependencies: ['isort[pyproject]']
    - repo: https://github.com/ambv/black
      rev: 20.8b1
      hooks:
          - id: black
            language_version: python3.7
    - repo: https://gitlab.com/pycqa/flake8
      rev: 3.8.4
      hooks:
          - id: flake8


default_language_version:
    python: python3.7
